version: "3"
services:
  paddle:
    image: ghcr.io/luler/reverse_image_search:latest
    restart: always
    environment:
      - JWT_SECRET=s@Q$eubj #安全起见，更换为复杂秘钥
    ports:
      - 4456:5000
    volumes:
      - .:/root/work
  nginx:
    image: nginx:1.21.6
    restart: always
    ports:
      - 8899:80
    volumes:
      - ./log/nginx_logs:/var/log/nginx
      - ./web/dist:/home/wwwroot/web/dist
      - ./static:/home/wwwroot/resource/static
      - ./config/nginx/conf.d:/etc/nginx/conf.d
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    restart: always
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./log/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./log/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    image: milvusdb/milvus:v2.1.4
    restart: always
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./log/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
  attu:
    image: zilliz/attu
    restart: always
    ports:
      - 30000:3000
    environment:
      MILVUS_URL: standalone:19530
